### ISSUE TITLE
`make docker up`  not working after changing port from 8080 to 8081

### ISSUE THREAD

**Issue by sacsand** [LeafyCode/survive-together-api#1]
#### Issue description
i have changed the ports of HASURA endpoints  in the .env file from 8080 to 8081 (since the 8080 taken by the system)

my env
```
POSTGRES_USER=survivetestuser
POSTGRES_PASSWORD=stpostgresuser123
POSTGRES_DB=survivedb
HASURA_GRAPHQL_ENDPOINT=http://localhost:8081/v1/graphql
HASURA_ENDPOINT=http://localhost:8081
HASURA_GRAPHQL_ADMIN_SECRET=secret
```

 Then run  `make docker up` got below error message,

`
ERROR: for survive-together-api-master_graphql-engine_1  Cannot start service graphql-engine: driver failed programming external connectivity on endpoint survive-together-api-master_graphql-engine_1 (c527806f8783164043c739fd86b152e7ae74e24ba042d82c2a294d9e9eaa3d97): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use

`

`Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use`
seems the docker-composer won't detect the port change.

#### Debugging 
I change the docker-composer port value from  8080:8080 to 8081:8080 and run the ` make docker up` . Then the build was successful. 

```
graphql-engine:
    image: hasura/graphql-engine:v1.1.1
    ports:
      - "8081:8080"
```
if we can pass port from .env file , issue will be solved,, :) 

**Suggested solution** 

add new .env variable to get the graphql port value

```
HASURA_GRAPHQL_PORT:8081

```
and change the docker-composer to get port value from .env,
 - ${HASURA_GRAPHQL_PORT}:8080

``` 
  graphql-engine:
   -------
    ports: 
      - ${HASURA_GRAPHQL_PORT:-8080}:8080


```
Tested this on my local and  working fine,

Thanks.

**Comment by THPubs** [comment]
Awesome! Please go ahead and create a PR. 🙂

**Comment by sacsand** [comment]
cool  :)
